# ==========================================
# DEVELOPMENT RECAPTCHA CONFIGURATION
# ==========================================
recaptcha.enabled=false
recaptcha.site-key=6LebOGgtAAAAAICdniWguB6ag-3qh0CFyBVzCkdj
recaptcha.secret-key=6LebOGgtAAAAAJ3aefcF6jjwzQIBOLolpM6xz5aH
recaptcha.score-threshold=0.5
recaptcha.verify-url=https://www.google.com/recaptcha/api/siteverify
