
CREATE TABLE IF NOT EXISTS countries (
    id BIGSERIAL PRIMARY KEY,
    admin_id BIGINT,
    name VARCHAR(120) NOT NULL UNIQUE,
    isActive BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL,
    CONSTRAINT fk_country_admin FOREIGN KEY (admin_id) REFERENCES admins(id)
);