CREATE TABLE IF NOT EXISTS disability_status (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    admin_id BIGINT,

    value VARCHAR(100),

    status BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_disability_status_admin
        FOREIGN KEY (admin_id)
            REFERENCES admins(id),

    CONSTRAINT uk_disability_status_value_admin
        UNIQUE (value, admin_id)

);