CREATE TABLE IF NOT EXISTS disability_isActive (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    admin_id BIGINT,

    value VARCHAR(100),

    isActive BOOLEAN DEFAULT TRUE,

    CONSTRAINT fk_disability_isActive_admin
        FOREIGN KEY (admin_id)
            REFERENCES admins(id),

    CONSTRAINT uk_disability_isActive_value_admin
        UNIQUE (value, admin_id)

);