CREATE TABLE drinking (

                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                          value VARCHAR(100),

                          admin_id BIGINT,

                          isActive BOOLEAN DEFAULT TRUE,

                          CONSTRAINT fk_drinking_admin
                              FOREIGN KEY (admin_id)
                                  REFERENCES admins(id),

                          CONSTRAINT uk_drinking_value_admin
                              UNIQUE (value, admin_id)

);