CREATE TABLE family_status (

                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               name VARCHAR(100),

                               admin_id BIGINT,

                               status BOOLEAN DEFAULT TRUE,

                               CONSTRAINT fk_family_status_admin
                                   FOREIGN KEY (admin_id)
                                       REFERENCES admins(id),

                               CONSTRAINT uk_family_status_name_admin
                                   UNIQUE (name, admin_id)

);