CREATE TABLE heights (

                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                         admin_id BIGINT,

                         height VARCHAR(20),

                         status BOOLEAN DEFAULT TRUE,

                         CONSTRAINT fk_height_admin
                             FOREIGN KEY (admin_id)
                                 REFERENCES admins(id),

                         CONSTRAINT uk_height_admin
                             UNIQUE (height, admin_id)

);