CREATE TABLE castes (

                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        admin_id BIGINT,

                        name VARCHAR(150) NOT NULL,

                        religion_id BIGINT,

                        isActive BOOLEAN DEFAULT TRUE,

                        CONSTRAINT fk_caste_admin
                            FOREIGN KEY (admin_id)
                                REFERENCES admins(id),

                        CONSTRAINT fk_caste_religion
                            FOREIGN KEY (religion_id)
                                REFERENCES religions(id),

                        CONSTRAINT uk_caste_name_religion
                            UNIQUE (name, religion_id)

);