CREATE TABLE complexions (

                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                             admin_id BIGINT,

                             value VARCHAR(100),

                             isActive BOOLEAN DEFAULT TRUE,

                             CONSTRAINT fk_complexion_admin
                                 FOREIGN KEY (admin_id)
                                     REFERENCES admins(id),

                             CONSTRAINT uk_complexion_value_admin
                                 UNIQUE (value, admin_id)

);