CREATE TABLE diets (

                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                       admin_id BIGINT,

                       name VARCHAR(100),

                       status BOOLEAN DEFAULT TRUE,

                       CONSTRAINT fk_diet_admin
                           FOREIGN KEY (admin_id)
                               REFERENCES admins(id),

                       CONSTRAINT uk_diet_name_admin
                           UNIQUE (name, admin_id)

);