CREATE TABLE education_levels (

                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                                  admin_id BIGINT,

                                  name VARCHAR(150) NOT NULL,

                                  status BOOLEAN NOT NULL DEFAULT TRUE,

                                  created_at TIMESTAMP NULL,

                                  updated_at TIMESTAMP NULL,

                                  CONSTRAINT fk_education_level_admin
                                      FOREIGN KEY (admin_id)
                                          REFERENCES admins(id),

                                  CONSTRAINT uk_education_level_name_admin
                                      UNIQUE (name, admin_id)

);