CREATE TABLE family_types (

                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                              admin_id BIGINT,

                              name VARCHAR(100) NOT NULL,

                              status BOOLEAN NOT NULL DEFAULT TRUE,

                              created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              updated_at TIMESTAMP NULL,

                              CONSTRAINT fk_family_type_admin
                                  FOREIGN KEY (admin_id)
                                      REFERENCES admins(id),

                              CONSTRAINT uk_family_type_name_admin
                                  UNIQUE (name, admin_id)

);