-- Add more comprehensive religions data

INSERT INTO religions (
    admin_id,
    name,
    is_active,
    created_at,
    updated_at
) VALUES
(NULL, 'Hindu', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Muslim', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Christian', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Sikh', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Buddhist', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Jain', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Parsi/Zoroastrian', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Jewish', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Muslim', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Christian', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Sikh', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Buddhist', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Jain', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Parsi', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Jewish', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Baháʼí', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Zoroastrian', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Shinto', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Taoist', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Confucian', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Other', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'No Religion', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Prefer Not to Say', TRUE, CURRENT_TIMESTAMP, NULL)
ON CONFLICT (name) DO NOTHING;
