-- Add more comprehensive education levels data

INSERT INTO education_levels (
    admin_id,
    name,
    is_active,
    created_at,
    updated_at
) VALUES
-- School Education
(NULL, 'No Schooling', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Primary School', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Middle School', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'High School', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'SSC', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'HSC', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, '10th Pass', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, '12th Pass', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Intermediate', TRUE, CURRENT_TIMESTAMP, NULL),

-- Undergraduate
(NULL, 'Diploma', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Certificate Course', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'ITI', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.A.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.Com.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.Sc.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.E.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.Tech.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.Arch.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.B.A.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.C.A.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'LLB', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'MBBS', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'BDS', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.Pharma', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.Ed.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'B.P.Ed.', TRUE, CURRENT_TIMESTAMP, NULL),

-- Postgraduate
(NULL, 'M.A.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Com.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Sc.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.E.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Tech.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Arch.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.B.A.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.C.A.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'LLM', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'MD', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'MS', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'MDS', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Pharma', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Ed.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.P.Ed.', TRUE, CURRENT_TIMESTAMP, NULL),

-- Professional Courses
(NULL, 'CA', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'CS', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'ICWA', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'CFA', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'CMA', TRUE, CURRENT_TIMESTAMP, NULL),

-- Doctorate
(NULL, 'Ph.D.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'M.Phil.', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Post Doctorate', TRUE, CURRENT_TIMESTAMP, NULL),

-- Other
(NULL, 'Under Graduate', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Graduate', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Post Graduate', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Professional', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Other', TRUE, CURRENT_TIMESTAMP, NULL),
(NULL, 'Prefer Not to Say', TRUE, CURRENT_TIMESTAMP, NULL)
ON CONFLICT (name) DO NOTHING;
