CREATE TABLE cities (

                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                        admin_id BIGINT,

                        name VARCHAR(120) NOT NULL,

                        state_id BIGINT NOT NULL,

                        status BOOLEAN NOT NULL DEFAULT TRUE,

                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

                        updated_at TIMESTAMP NULL,

                        CONSTRAINT fk_city_admin
                            FOREIGN KEY (admin_id)
                                REFERENCES admins(id),

                        CONSTRAINT fk_city_state
                            FOREIGN KEY (state_id)
                                REFERENCES states(id),

                        CONSTRAINT uk_city_name_state
                            UNIQUE (name, state_id)

);