CREATE TABLE family_isActive (

                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

                               name VARCHAR(100),

                               admin_id BIGINT,

                               isActive BOOLEAN DEFAULT TRUE,

                               CONSTRAINT fk_family_isActive_admin
                                   FOREIGN KEY (admin_id)
                                       REFERENCES admins(id),

                               CONSTRAINT uk_family_isActive_name_admin
                                   UNIQUE (name, admin_id)

);